apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ansible-playbook-template
  title: Create an Ansible Project
  description: Create an Ansible Playbook to deploy environment
  tags:
    - recommended
    - ansible
spec:
  owner: rhdh
  type: service
  parameters:
    - title: Provide Information for Application
      required:
        - component_id
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
          default: ansible-playbook
          ui:field: EntityNamePicker
          maxLength: 23
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
          default: An ansible playbook

    - title: Application repository Information
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development
        deployToCluster:
          title: Deploy to a cluster?
          type: boolean
          default: true

      dependencies:
        deployToCluster:
          allOf:
            - if:
                properties:
                  deployToCluster:
                    const: true
              then:
                properties:
                  cluster:
                    title: Cluster Url
                    type: string
                    description: The cluster to host the play
                required:
                  - cluster

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutTemplating:
          - .github/workflows/*
        values:
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          namespace: ${{ parameters.component_id }}-dev
          owner: ${{ user.entity.metadata.name }}
          cluster: ${{ parameters.cluster }}
          host: ${{ parameters.repo.host }}
          destination: ${{ parameters.repo.owner }}/${{ parameters.component_id }}
          port: 8080

    - id: publish
      name: Publish
      action: publish:gitlab
      input:
        repoUrl: "${{ parameters.repo.host }}?owner=${{ parameters.repo.owner }}&repo=${{parameters.component_id}}"
        repoVisibility: public

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
